main: primero.PrimerPlugin
name: PrimerPlugin
version: 1.0
author: Romplestinskin
description: -no desc-
commands:
  market:
    description: Displays the gamerz market.
  price:
    description: put a price on item, /price price item id